CREATE TABLE CART (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	customer_id INT(30) UNSIGNED NOT NULL,
	product_id INT(30) UNSIGNED NOT NULL,
	quantity INT(100) UNSIGNED NOT NULL,
    PRIMARY KEY ( id ),
	FOREIGN KEY ( customer_id ) REFERENCES CUSTOMERS ( id ),
	FOREIGN KEY ( product_id ) REFERENCES PRODUCTS ( id )
);