CREATE TABLE PRODUCTS (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL, 
	name VARCHAR(100) NOT NULL,
	price INT UNSIGNED NOT NULL,
	inventory INT UNSIGNED NOT NULL,
	image_ref VARCHAR(1000) NOT NULL,
	category VARCHAR(1000) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	removed TINYINT(1) NOT NULL,
    PRIMARY KEY ( id )
);